FROM public.ecr.aws/lambda/python:3.11

RUN yum update -y
RUN yum install -y gnupg2 wget curl --nogpgcheck

# Install google chrome
RUN yum update -y
COPY ../driver/google-chrome-stable-114.0.5735.198-1.x86_64.rpm /tmp/chrome.rpm
RUN yum install -y /tmp/chrome.rpm --nogpgcheck && rm /tmp/chrome.rpm

# Installing Unzip
RUN yum install -yqq unzip --nogpgcheck

# Add chrome driver
COPY ../driver/chromedriver_linux64.zip /tmp/chromedriver.zip

# Unzip the Chrome Driver into /usr/local/bin directory
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

# Set display port as an environment variable
ENV DISPLAY=:99