FROM public.ecr.aws/lambda/python:3.11

RUN yum update -y
RUN yum install -y gnupg2 wget curl --nogpgcheck

#RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

RUN yum update -y
COPY ../docker_files/google-chrome-stable-114.0.5735.198-1.x86_64.rpm /tmp/chrome.rpm
RUN yum install -y /tmp/chrome.rpm --nogpgcheck && rm /tmp/chrome.rpm

#ARG CHROME_VERSION="114.0.5735.198"
#RUN wget --no-verbose -O /tmp/chrome.rpm https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-${GOOGLE_CHROME_VERSION}-1.x86_64.rpm \
#  && yum install -y /tmp/chrome.rpm --nogpgcheck \
#  && rm /tmp/chrome.rpm

# Installing Unzip
RUN yum install -yqq unzip --nogpgcheck

# Download the Chrome Driver
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip

# Unzip the Chrome Driver into /usr/local/bin directory
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

# Set display port as an environment variable
ENV DISPLAY=:99